spring:
  application:
   name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8071

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% sampling (use less in production)
            