spring:
  config:
    import: "configserver:"
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
  application:
    name: organization-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/twopages-realm/protocol/openid-connect/certs